{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc-autoconfigure",
    "version": "0.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.5.7-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.5.7-plain.jar",
          "size": 14677,
          "sha512": "bc530ba31fc8f6d05ef5d2dbe5a82b04a9656063509f7eab62127ade5f75b796dbf49b2805f75dfd8b2321e6c7656fd2879ffb9f8ddcd4462e89cc4061c19a82",
          "sha256": "7f6fd8e1dedbff84b6bff075c5a74f8d17bb345da14e2b89f55a2beba9c5a2bc",
          "sha1": "fb5b49410f8eb335c7461f5511b261d2afbece9c",
          "md5": "1b06f8698a9926359d7825561e879435"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.5.7-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.5.7-plain.jar",
          "size": 14677,
          "sha512": "bc530ba31fc8f6d05ef5d2dbe5a82b04a9656063509f7eab62127ade5f75b796dbf49b2805f75dfd8b2321e6c7656fd2879ffb9f8ddcd4462e89cc4061c19a82",
          "sha256": "7f6fd8e1dedbff84b6bff075c5a74f8d17bb345da14e2b89f55a2beba9c5a2bc",
          "sha1": "fb5b49410f8eb335c7461f5511b261d2afbece9c",
          "md5": "1b06f8698a9926359d7825561e879435"
        }
      ]
    }
  ]
}
