{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc-autoconfigure",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.4.4-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.4.4-plain.jar",
          "size": 14677,
          "sha512": "062620830f838d46db94ffae6a2fd7e9f310fbccf0f5118875bf92d6bdc91020d302746547b6b55fc4bd54f1cc97d42ccfdf7845109edc4026750efe21163672",
          "sha256": "0c433cfa7a092f2a11f155946ee757c93d5ce3f35aecbcb7be0bb180db39769f",
          "sha1": "2d3dee57fd57b2918013547a7d9fbbe144488b91",
          "md5": "03d1244090fcb81f331ffdbba1a96537"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.4.4-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.4.4-plain.jar",
          "size": 14677,
          "sha512": "062620830f838d46db94ffae6a2fd7e9f310fbccf0f5118875bf92d6bdc91020d302746547b6b55fc4bd54f1cc97d42ccfdf7845109edc4026750efe21163672",
          "sha256": "0c433cfa7a092f2a11f155946ee757c93d5ce3f35aecbcb7be0bb180db39769f",
          "sha1": "2d3dee57fd57b2918013547a7d9fbbe144488b91",
          "md5": "03d1244090fcb81f331ffdbba1a96537"
        }
      ]
    }
  ]
}
