{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-kotlin-spring-webflux-upload",
    "version": "0.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux"
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-webflux-upload-0.5.6-plain.jar",
          "url": "graphql-kotlin-spring-webflux-upload-0.5.6-plain.jar",
          "size": 24252,
          "sha512": "ddee6c30549a8de2905bd99a52d30a8a6a3453579642127ee7b36d770f39adb1acee5fa6f67c1a415e79429fdf02ad9f561339abb2d19b27bea8d6b8009f9377",
          "sha256": "64fa10fa702446810da8b8090c2e87597e5cd28aab9e5e90633c22bb2a5f9bf9",
          "sha1": "3362d1e977229219318860571c51fe080329b87b",
          "md5": "74783c8ee77ed0a74b6a8023fba802b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux"
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-webflux-upload-0.5.6-plain.jar",
          "url": "graphql-kotlin-spring-webflux-upload-0.5.6-plain.jar",
          "size": 24252,
          "sha512": "ddee6c30549a8de2905bd99a52d30a8a6a3453579642127ee7b36d770f39adb1acee5fa6f67c1a415e79429fdf02ad9f561339abb2d19b27bea8d6b8009f9377",
          "sha256": "64fa10fa702446810da8b8090c2e87597e5cd28aab9e5e90633c22bb2a5f9bf9",
          "sha1": "3362d1e977229219318860571c51fe080329b87b",
          "md5": "74783c8ee77ed0a74b6a8023fba802b1"
        }
      ]
    }
  ]
}
