{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-core",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-core-0.4.3.jar",
          "url": "graphql-core-0.4.3.jar",
          "size": 46424,
          "sha512": "205fb3d52518427252eaed2c5b9fef8c5ecf29afe28a02c64f23c2d03212480287925e3e3ffb36faaf072f78817b7e7fac75a73e75c6cff44553062d7ae22e6f",
          "sha256": "210ec7a44419fc9d04958494fd8e8ca8879749b5d2aeccd94b608072c250fc11",
          "sha1": "df0b1c7f733827bb940132eb938ecad1ea4e0766",
          "md5": "42c03b53c19d401ad87c948397fca6dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-core-0.4.3.jar",
          "url": "graphql-core-0.4.3.jar",
          "size": 46424,
          "sha512": "205fb3d52518427252eaed2c5b9fef8c5ecf29afe28a02c64f23c2d03212480287925e3e3ffb36faaf072f78817b7e7fac75a73e75c6cff44553062d7ae22e6f",
          "sha256": "210ec7a44419fc9d04958494fd8e8ca8879749b5d2aeccd94b608072c250fc11",
          "sha1": "df0b1c7f733827bb940132eb938ecad1ea4e0766",
          "md5": "42c03b53c19d401ad87c948397fca6dd"
        }
      ]
    }
  ]
}
