{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc-autoconfigure",
    "version": "0.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.5.6-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.5.6-plain.jar",
          "size": 14677,
          "sha512": "85f4e331dd65094c0e648d3643e685727b8eb4332496adc0713950100a00f3a6e60bfc70a95d05c4dedcbef81bb29619d93255ef51f3025094519241523ade1e",
          "sha256": "b5e70dd4dbd54f4fc8defdd9998a3efcc2d6318e373a161389174be563a5e7b5",
          "sha1": "10dbfa070c22c7d9cb12850b344df3b59527f3db",
          "md5": "4e65c92ff38917ed42e61ee35c6f5397"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.5.6-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.5.6-plain.jar",
          "size": 14677,
          "sha512": "85f4e331dd65094c0e648d3643e685727b8eb4332496adc0713950100a00f3a6e60bfc70a95d05c4dedcbef81bb29619d93255ef51f3025094519241523ade1e",
          "sha256": "b5e70dd4dbd54f4fc8defdd9998a3efcc2d6318e373a161389174be563a5e7b5",
          "sha1": "10dbfa070c22c7d9cb12850b344df3b59527f3db",
          "md5": "4e65c92ff38917ed42e61ee35c6f5397"
        }
      ]
    }
  ]
}
