{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-commons",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons"
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-commons-0.4.5-plain.jar",
          "url": "spring-data-graphql-commons-0.4.5-plain.jar",
          "size": 4988,
          "sha512": "41ce5173080cba41f32275e3cf581a74df4ea34675df0edd6ef6c399a8a3de817fe2152f2751c27335e23b91e98cc5ebeae963673c58d17133dfeac41fcce1e0",
          "sha256": "3acc08bd30e05c1c8d850788dc47bdd0902c149d832e16c098e1d9f7edcbfdb5",
          "sha1": "4afc486dfa9fd8f8891966696bbf0914360ee390",
          "md5": "ef9d84c8ce659182f34059053b82d63b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons"
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-commons-0.4.5-plain.jar",
          "url": "spring-data-graphql-commons-0.4.5-plain.jar",
          "size": 4988,
          "sha512": "41ce5173080cba41f32275e3cf581a74df4ea34675df0edd6ef6c399a8a3de817fe2152f2751c27335e23b91e98cc5ebeae963673c58d17133dfeac41fcce1e0",
          "sha256": "3acc08bd30e05c1c8d850788dc47bdd0902c149d832e16c098e1d9f7edcbfdb5",
          "sha1": "4afc486dfa9fd8f8891966696bbf0914360ee390",
          "md5": "ef9d84c8ce659182f34059053b82d63b"
        }
      ]
    }
  ]
}
