{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-jetpack-starter",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-jetpack-autoconfigure",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-hooks-provider",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-security-jwt-webflux",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-starter-0.5.3-plain.jar",
          "url": "graphql-jetpack-starter-0.5.3-plain.jar",
          "size": 261,
          "sha512": "fb16d6e00e5a44de48e99f0e16d59b3bde24966e4d646ca1c3b39b780d0a4b1b89ea3055f120a5137479a20f68a91b4d82acc1022fd4fe74737cb3725db30d11",
          "sha256": "812711228c9c32f65dfaaa308ffa1b7c826a86c4d3ff7cf0ba6a202437efc23f",
          "sha1": "3764a8c6db2057a122cbd8b9c671634e04296926",
          "md5": "9d87dc6f68c6ae9932cc1fd5316b021b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-jetpack-autoconfigure",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-hooks-provider",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-security-jwt-webflux",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-starter-0.5.3-plain.jar",
          "url": "graphql-jetpack-starter-0.5.3-plain.jar",
          "size": 261,
          "sha512": "fb16d6e00e5a44de48e99f0e16d59b3bde24966e4d646ca1c3b39b780d0a4b1b89ea3055f120a5137479a20f68a91b4d82acc1022fd4fe74737cb3725db30d11",
          "sha256": "812711228c9c32f65dfaaa308ffa1b7c826a86c4d3ff7cf0ba6a202437efc23f",
          "sha1": "3764a8c6db2057a122cbd8b9c671634e04296926",
          "md5": "9d87dc6f68c6ae9932cc1fd5316b021b"
        }
      ]
    }
  ]
}
