{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc-starter",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc-autoconfigure",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-starter-0.4.0-plain.jar",
          "url": "spring-data-graphql-r2dbc-starter-0.4.0-plain.jar",
          "size": 261,
          "sha512": "d346a1755d223733f9020af70ce8ef7af7e5038952c50a01090801ef12021143f411ec43f8ae759f3f36a2d35fb2b57c5b49707cd2bacdf20cdc3ef041ce7938",
          "sha256": "6da6fca9ccf85008c6b1a239da4434083f82939a892614dfdba3f42c67d4d1bc",
          "sha1": "88f1af98c8d51209f4f77a93c117357388877c25",
          "md5": "5dcbd125d157f051b5cdc903bb6bfebf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc-autoconfigure",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-starter-0.4.0-plain.jar",
          "url": "spring-data-graphql-r2dbc-starter-0.4.0-plain.jar",
          "size": 261,
          "sha512": "d346a1755d223733f9020af70ce8ef7af7e5038952c50a01090801ef12021143f411ec43f8ae759f3f36a2d35fb2b57c5b49707cd2bacdf20cdc3ef041ce7938",
          "sha256": "6da6fca9ccf85008c6b1a239da4434083f82939a892614dfdba3f42c67d4d1bc",
          "sha1": "88f1af98c8d51209f4f77a93c117357388877c25",
          "md5": "5dcbd125d157f051b5cdc903bb6bfebf"
        }
      ]
    }
  ]
}
