{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-commons",
    "version": "0.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons"
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-relational"
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-commons-0.5.7-plain.jar",
          "url": "spring-data-graphql-commons-0.5.7-plain.jar",
          "size": 6818,
          "sha512": "f39c56c63cf4137c63ff86cade02e1c53762834e10d66f9f51f2ba0d1f2fe1584113e1424674958fff626f32cb73b8a1e11eafb4fcab0e75358967734bed1ef3",
          "sha256": "4e9d4bedb62124bac6e9260db300770cb0939b5477105e0db13b04b71248fda3",
          "sha1": "faea34a6a0a8202fc117c2ddcbf2eaf7d49f53eb",
          "md5": "6c3f29fcc5bd934523cc909e78adc330"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons"
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-relational"
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-commons-0.5.7-plain.jar",
          "url": "spring-data-graphql-commons-0.5.7-plain.jar",
          "size": 6818,
          "sha512": "f39c56c63cf4137c63ff86cade02e1c53762834e10d66f9f51f2ba0d1f2fe1584113e1424674958fff626f32cb73b8a1e11eafb4fcab0e75358967734bed1ef3",
          "sha256": "4e9d4bedb62124bac6e9260db300770cb0939b5477105e0db13b04b71248fda3",
          "sha1": "faea34a6a0a8202fc117c2ddcbf2eaf7d49f53eb",
          "md5": "6c3f29fcc5bd934523cc909e78adc330"
        }
      ]
    }
  ]
}
