{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-postgresql-scalars",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.8.10.RELEASE"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-postgresql-scalars-0.4.4.jar",
          "url": "graphql-postgresql-scalars-0.4.4.jar",
          "size": 10826,
          "sha512": "71fe1ba0bd2725b5eeedc261c67b333f4a608aba5b16cbd40ec1a6eec62fe889d3eb2738db3eaf5a977b994c53ba43ff39755e925f04df7adda993728158470a",
          "sha256": "84f36657b0bcfa3278d616cecd98040f25415c2b8ebaae5c79d43bf9bd2009a9",
          "sha1": "000364a97393b3e574a03c2d1b13365953bf791e",
          "md5": "fb2be349c3af3f151bd4df928f9a968a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.8.10.RELEASE"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-postgresql-scalars-0.4.4.jar",
          "url": "graphql-postgresql-scalars-0.4.4.jar",
          "size": 10826,
          "sha512": "71fe1ba0bd2725b5eeedc261c67b333f4a608aba5b16cbd40ec1a6eec62fe889d3eb2738db3eaf5a977b994c53ba43ff39755e925f04df7adda993728158470a",
          "sha256": "84f36657b0bcfa3278d616cecd98040f25415c2b8ebaae5c79d43bf9bd2009a9",
          "sha1": "000364a97393b3e574a03c2d1b13365953bf791e",
          "md5": "fb2be349c3af3f151bd4df928f9a968a"
        }
      ]
    }
  ]
}
