{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-jetpack-starter",
    "version": "0.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-jetpack-autoconfigure",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-hooks-provider",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-security-jwt-webflux",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-starter-0.5.8-plain.jar",
          "url": "graphql-jetpack-starter-0.5.8-plain.jar",
          "size": 261,
          "sha512": "a97dbf1ff11f5abd4fb321c43903b61e0d3ab1e52353f00eac01e5035383ff09ecbdc0a88df9748b4e122d145614c89fd417776bf41a43f7b61d5e5f83009afc",
          "sha256": "15f99a0f3d71f9f8ca5b4a463e6a7f5b324884ad0ea626b342bc9986e0f5b9f5",
          "sha1": "9b68c49360545530fe6165586499171f5a788810",
          "md5": "a948c70dec621200df3e463d3055b8be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-jetpack-autoconfigure",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-hooks-provider",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-security-jwt-webflux",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-starter-0.5.8-plain.jar",
          "url": "graphql-jetpack-starter-0.5.8-plain.jar",
          "size": 261,
          "sha512": "a97dbf1ff11f5abd4fb321c43903b61e0d3ab1e52353f00eac01e5035383ff09ecbdc0a88df9748b4e122d145614c89fd417776bf41a43f7b61d5e5f83009afc",
          "sha256": "15f99a0f3d71f9f8ca5b4a463e6a7f5b324884ad0ea626b342bc9986e0f5b9f5",
          "sha1": "9b68c49360545530fe6165586499171f5a788810",
          "md5": "a948c70dec621200df3e463d3055b8be"
        }
      ]
    }
  ]
}
