{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "kotlin-coroutine-reactive-extensions",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-coroutine-reactive-extensions-0.4.5.jar",
          "url": "kotlin-coroutine-reactive-extensions-0.4.5.jar",
          "size": 8778,
          "sha512": "6fb5b6dda1a61d3e52257471edc9842b575ce2f16a47a44ca2f9d1aeb46c9aa05d622110362c31dbb9c8d49d8c89c359b06819069ee03304ba5938019e7c49bb",
          "sha256": "651d154783ff868fc00c2697cc5fd0c197fee4ba8414755d0cdd77d5c1920f2d",
          "sha1": "9a6485d0747031b31941a2ef065c1a0554c5846f",
          "md5": "c061860d8f7129abec852b9f1df9248d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-coroutine-reactive-extensions-0.4.5.jar",
          "url": "kotlin-coroutine-reactive-extensions-0.4.5.jar",
          "size": 8778,
          "sha512": "6fb5b6dda1a61d3e52257471edc9842b575ce2f16a47a44ca2f9d1aeb46c9aa05d622110362c31dbb9c8d49d8c89c359b06819069ee03304ba5938019e7c49bb",
          "sha256": "651d154783ff868fc00c2697cc5fd0c197fee4ba8414755d0cdd77d5c1920f2d",
          "sha1": "9a6485d0747031b31941a2ef065c1a0554c5846f",
          "md5": "c061860d8f7129abec852b9f1df9248d"
        }
      ]
    }
  ]
}
