{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-commons",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "java-dataloader",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-0.5.0-plain.jar",
          "url": "spring-data-graphql-r2dbc-0.5.0-plain.jar",
          "size": 246359,
          "sha512": "b66b479a68a4e3bff6e67af22671cf844afc9981c99dd63ab38c5600e5d7c9cd69860d18f0d8c9acae0fbc63659ffebe443f561c5b9237f001957d07d13b0fd6",
          "sha256": "3a26e9d11916a9d96d6b5dd1abdcc9f70f47d0412027c9f1e594a8b7a1a09eb6",
          "sha1": "a3a08820065e7b67ee0f670193f05c656f6f33e9",
          "md5": "6e9681edd6dd1b9157ee1856a3f592eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-commons",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "java-dataloader",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-0.5.0-plain.jar",
          "url": "spring-data-graphql-r2dbc-0.5.0-plain.jar",
          "size": 246359,
          "sha512": "b66b479a68a4e3bff6e67af22671cf844afc9981c99dd63ab38c5600e5d7c9cd69860d18f0d8c9acae0fbc63659ffebe443f561c5b9237f001957d07d13b0fd6",
          "sha256": "3a26e9d11916a9d96d6b5dd1abdcc9f70f47d0412027c9f1e594a8b7a1a09eb6",
          "sha1": "a3a08820065e7b67ee0f670193f05c656f6f33e9",
          "md5": "6e9681edd6dd1b9157ee1856a3f592eb"
        }
      ]
    }
  ]
}
