{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-postgresql-scalars",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.8.10.RELEASE"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-postgresql-scalars-0.5.1.jar",
          "url": "graphql-postgresql-scalars-0.5.1.jar",
          "size": 10826,
          "sha512": "f08cac79bceb76263b50db6d5b4deea8d69b86cec04efa1dd19cafd0c25058b670e1cfe988877d9b172e6c31f85b85efcdac2184c3e716d050eec2fed3ec3808",
          "sha256": "a74c0d12b99c3f7005620eb09754a56506e08c0e7b2fef1c8790e76d4f04cc12",
          "sha1": "ef293541127b50b5705432fe3d44fe702605631b",
          "md5": "0a84032df8ecb18dde199d9078f7ad64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.8.10.RELEASE"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-postgresql-scalars-0.5.1.jar",
          "url": "graphql-postgresql-scalars-0.5.1.jar",
          "size": 10826,
          "sha512": "f08cac79bceb76263b50db6d5b4deea8d69b86cec04efa1dd19cafd0c25058b670e1cfe988877d9b172e6c31f85b85efcdac2184c3e716d050eec2fed3ec3808",
          "sha256": "a74c0d12b99c3f7005620eb09754a56506e08c0e7b2fef1c8790e76d4f04cc12",
          "sha1": "ef293541127b50b5705432fe3d44fe702605631b",
          "md5": "0a84032df8ecb18dde199d9078f7ad64"
        }
      ]
    }
  ]
}
