{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "kotlin-coroutine-reactive-extensions",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-coroutine-reactive-extensions-0.4.4.jar",
          "url": "kotlin-coroutine-reactive-extensions-0.4.4.jar",
          "size": 8778,
          "sha512": "1eeb885958870f725f96556689c97bae014f438b6e2a599129349633a44a50c2243b589bb88b2050c461627b136eb3e5a81bffd18a6f4d2ae9160b8f065fb2ee",
          "sha256": "43d9556a86ab8d0d66241bf7c7a6b55e8482898706a4c2fbe5b2f764c72a4ba0",
          "sha1": "9206a92c7cfd4575eeb7276607689b21568a79b3",
          "md5": "8cf0e6a5dc7d24911fab9e8071febef5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-coroutine-reactive-extensions-0.4.4.jar",
          "url": "kotlin-coroutine-reactive-extensions-0.4.4.jar",
          "size": 8778,
          "sha512": "1eeb885958870f725f96556689c97bae014f438b6e2a599129349633a44a50c2243b589bb88b2050c461627b136eb3e5a81bffd18a6f4d2ae9160b8f065fb2ee",
          "sha256": "43d9556a86ab8d0d66241bf7c7a6b55e8482898706a4c2fbe5b2f764c72a4ba0",
          "sha1": "9206a92c7cfd4575eeb7276607689b21568a79b3",
          "md5": "8cf0e6a5dc7d24911fab9e8071febef5"
        }
      ]
    }
  ]
}
