{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "kotlin-coroutine-reactive-extensions",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-coroutine-reactive-extensions-0.4.0.jar",
          "url": "kotlin-coroutine-reactive-extensions-0.4.0.jar",
          "size": 8778,
          "sha512": "b60be3400b3034dd08b3d92133e8106e82d11b423816cad5785061f31ff87f3d0238bfb544e88675df9a534c0f6684f473057047f9a24f2eedf1e199cede4948",
          "sha256": "34daf8828caea32bdafa4d81a77015c6504a82e3e28bffcecf137b5d1ae64272",
          "sha1": "31ca20344d797f71206c5bd049088d82c1ff48a4",
          "md5": "ecdfec80403f9844a001e74ba7216508"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-coroutine-reactive-extensions-0.4.0.jar",
          "url": "kotlin-coroutine-reactive-extensions-0.4.0.jar",
          "size": 8778,
          "sha512": "b60be3400b3034dd08b3d92133e8106e82d11b423816cad5785061f31ff87f3d0238bfb544e88675df9a534c0f6684f473057047f9a24f2eedf1e199cede4948",
          "sha256": "34daf8828caea32bdafa4d81a77015c6504a82e3e28bffcecf137b5d1ae64272",
          "sha1": "31ca20344d797f71206c5bd049088d82c1ff48a4",
          "md5": "ecdfec80403f9844a001e74ba7216508"
        }
      ]
    }
  ]
}
