{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-jetpack-autoconfigure",
    "version": "0.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-jetpack",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-kotlin-spring-security",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-kotlin-spring-webflux-upload",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-autoconfigure-0.4.7-plain.jar",
          "url": "graphql-jetpack-autoconfigure-0.4.7-plain.jar",
          "size": 10848,
          "sha512": "5b5e177e2c7cfaf049bfcdfe53b54c0debad1c3cc3c0fb93a7e002d1402424804ea673e31b4cb1b8d1b51faf0db998b55c49b28a3898e8113af4b41c30a3430c",
          "sha256": "d029ed98f14fbf4637bf8086cf875ca08201a0d8a3f9dc49f7b7f571a7b463eb",
          "sha1": "a98fce7953405fad28cefaf8bbd7172221e5b5ac",
          "md5": "5d34279fa4ea7b8ec2fe3a07acc4224b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-jetpack",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-kotlin-spring-security",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-kotlin-spring-webflux-upload",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-hooks-provider",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-security-jwt-webflux",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-autoconfigure-0.4.7-plain.jar",
          "url": "graphql-jetpack-autoconfigure-0.4.7-plain.jar",
          "size": 10848,
          "sha512": "5b5e177e2c7cfaf049bfcdfe53b54c0debad1c3cc3c0fb93a7e002d1402424804ea673e31b4cb1b8d1b51faf0db998b55c49b28a3898e8113af4b41c30a3430c",
          "sha256": "d029ed98f14fbf4637bf8086cf875ca08201a0d8a3f9dc49f7b7f571a7b463eb",
          "sha1": "a98fce7953405fad28cefaf8bbd7172221e5b5ac",
          "md5": "5d34279fa4ea7b8ec2fe3a07acc4224b"
        }
      ]
    }
  ]
}
