{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc-autoconfigure",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.4.5-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.4.5-plain.jar",
          "size": 14677,
          "sha512": "e15d0c0769a54406383ef0e59cd711560b841ce7f2dd2a279d38e4aad5ed3c44885758304e6ed0fff866104d2cdf9dc30fb31c91dc40bea00bac244f62cd4aa3",
          "sha256": "fba5f08eacd54a7b1c3bf12c96eeea5156c553b5d312e3a8d94e256ed4f82d8c",
          "sha1": "821ea23365681394b23975320206c143cd481b71",
          "md5": "30fb9618b640b59bb3081505b101abc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.4.5-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.4.5-plain.jar",
          "size": 14677,
          "sha512": "e15d0c0769a54406383ef0e59cd711560b841ce7f2dd2a279d38e4aad5ed3c44885758304e6ed0fff866104d2cdf9dc30fb31c91dc40bea00bac244f62cd4aa3",
          "sha256": "fba5f08eacd54a7b1c3bf12c96eeea5156c553b5d312e3a8d94e256ed4f82d8c",
          "sha1": "821ea23365681394b23975320206c143cd481b71",
          "md5": "30fb9618b640b59bb3081505b101abc4"
        }
      ]
    }
  ]
}
