{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-kotlin-spring-security",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        },
        {
          "group": "com.zhokhov.graphql",
          "module": "graphql-java-datetime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-security-0.4.4-plain.jar",
          "url": "graphql-kotlin-spring-security-0.4.4-plain.jar",
          "size": 12586,
          "sha512": "407c0d71f23870484b6ffb9fd5ca8a516193972f2c522c2332927d76b4a70cbf70fb74ccb407f27ed4893c80bb0954a9d3f455c25a6d1348066078dfad3e3fe8",
          "sha256": "60790349e4fc29869819c0edb471373e14ec0633488bdae44bbd07da53a34fc4",
          "sha1": "3ec9a7279c4563723bb95f8617791fd32961d8f0",
          "md5": "aa9b354e5c49c7aff6518f64b9405abe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        },
        {
          "group": "com.zhokhov.graphql",
          "module": "graphql-java-datetime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-security-0.4.4-plain.jar",
          "url": "graphql-kotlin-spring-security-0.4.4-plain.jar",
          "size": 12586,
          "sha512": "407c0d71f23870484b6ffb9fd5ca8a516193972f2c522c2332927d76b4a70cbf70fb74ccb407f27ed4893c80bb0954a9d3f455c25a6d1348066078dfad3e3fe8",
          "sha256": "60790349e4fc29869819c0edb471373e14ec0633488bdae44bbd07da53a34fc4",
          "sha1": "3ec9a7279c4563723bb95f8617791fd32961d8f0",
          "md5": "aa9b354e5c49c7aff6518f64b9405abe"
        }
      ]
    }
  ]
}
