{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc-autoconfigure",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.5.4-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.5.4-plain.jar",
          "size": 14677,
          "sha512": "5590e50766880ce0d958c6ee5796b35d6d46882a37412f6f768caac38ab9075f4915de6a7c9e4ef46bd5a9469f956130bf06db39b7bdfe080748471b1942cd06",
          "sha256": "e66301d005ce84b4322c24fc50c42cbab15db695bfc8e7d3fed823beda6b085f",
          "sha1": "59519a910397544901eec55314d846020606e9ec",
          "md5": "bbc5ab387fb03eb68a815d1980aa69fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.5.4-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.5.4-plain.jar",
          "size": 14677,
          "sha512": "5590e50766880ce0d958c6ee5796b35d6d46882a37412f6f768caac38ab9075f4915de6a7c9e4ef46bd5a9469f956130bf06db39b7bdfe080748471b1942cd06",
          "sha256": "e66301d005ce84b4322c24fc50c42cbab15db695bfc8e7d3fed823beda6b085f",
          "sha1": "59519a910397544901eec55314d846020606e9ec",
          "md5": "bbc5ab387fb03eb68a815d1980aa69fa"
        }
      ]
    }
  ]
}
