{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-postgresql-scalars",
    "version": "0.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.8.10.RELEASE"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-postgresql-scalars-0.4.7.jar",
          "url": "graphql-postgresql-scalars-0.4.7.jar",
          "size": 10826,
          "sha512": "3b5e1de556a26ea5d3a72035c842ad13e6b5d2d79ac82590127fbe38a5bc9dc50a0cf892c4f1c57e08acf5a89258b53f792b76abc9542f70f78c6c3db60638c4",
          "sha256": "9c6c3ff4271760b801ea825ba41cbc31eda5f97dbbdb0b00660ec97e4d7204ce",
          "sha1": "eccb8f8f38bb8172fbb03f89bf254a43ceeca7c3",
          "md5": "55562d67f00b0f0c0f6fedc1ccf4796f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.8.10.RELEASE"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-postgresql-scalars-0.4.7.jar",
          "url": "graphql-postgresql-scalars-0.4.7.jar",
          "size": 10826,
          "sha512": "3b5e1de556a26ea5d3a72035c842ad13e6b5d2d79ac82590127fbe38a5bc9dc50a0cf892c4f1c57e08acf5a89258b53f792b76abc9542f70f78c6c3db60638c4",
          "sha256": "9c6c3ff4271760b801ea825ba41cbc31eda5f97dbbdb0b00660ec97e4d7204ce",
          "sha1": "eccb8f8f38bb8172fbb03f89bf254a43ceeca7c3",
          "md5": "55562d67f00b0f0c0f6fedc1ccf4796f"
        }
      ]
    }
  ]
}
