{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-commons",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "java-dataloader",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-0.4.2-plain.jar",
          "url": "spring-data-graphql-r2dbc-0.4.2-plain.jar",
          "size": 218186,
          "sha512": "cd6f6043ec010d8ccac776a67cf8e3dcf158abee55830cd3b4ff4354e3a692bb88924505d86f5c5d002314c74ba79913d32a125fa22143190f06a3d1bd4d2c93",
          "sha256": "c9eb4a845062013c8c912d8745319200aa2a5bc42076c114149e57f6d315eafb",
          "sha1": "ae690ec840b8458928e17e0f7ad7fdad3aaf9a0a",
          "md5": "421fdd518cd1bada26833ea74c624418"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-commons",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "java-dataloader",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-0.4.2-plain.jar",
          "url": "spring-data-graphql-r2dbc-0.4.2-plain.jar",
          "size": 218186,
          "sha512": "cd6f6043ec010d8ccac776a67cf8e3dcf158abee55830cd3b4ff4354e3a692bb88924505d86f5c5d002314c74ba79913d32a125fa22143190f06a3d1bd4d2c93",
          "sha256": "c9eb4a845062013c8c912d8745319200aa2a5bc42076c114149e57f6d315eafb",
          "sha1": "ae690ec840b8458928e17e0f7ad7fdad3aaf9a0a",
          "md5": "421fdd518cd1bada26833ea74c624418"
        }
      ]
    }
  ]
}
