{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-kotlin-spring-webflux-upload",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux"
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-webflux-upload-0.4.5-plain.jar",
          "url": "graphql-kotlin-spring-webflux-upload-0.4.5-plain.jar",
          "size": 24252,
          "sha512": "ab30a8af8f216db9a5aa28e260898cfcc3a6edc93e77ad43e87b51dc4a4851b7e73135da8ad2ad843c3e4932fd7648164f6083ac52a0156fb049d415165630ff",
          "sha256": "eab099052f2da37fc79f5318991388fbdd2c19466cd9088d36bc916a48095b1b",
          "sha1": "303c5f9f544dcd67b1479a85bd28767135279806",
          "md5": "38397d647cb65fe92e8b231c6ad927a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux"
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-webflux-upload-0.4.5-plain.jar",
          "url": "graphql-kotlin-spring-webflux-upload-0.4.5-plain.jar",
          "size": 24252,
          "sha512": "ab30a8af8f216db9a5aa28e260898cfcc3a6edc93e77ad43e87b51dc4a4851b7e73135da8ad2ad843c3e4932fd7648164f6083ac52a0156fb049d415165630ff",
          "sha256": "eab099052f2da37fc79f5318991388fbdd2c19466cd9088d36bc916a48095b1b",
          "sha1": "303c5f9f544dcd67b1479a85bd28767135279806",
          "md5": "38397d647cb65fe92e8b231c6ad927a7"
        }
      ]
    }
  ]
}
