{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-kotlin-spring-security",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        },
        {
          "group": "com.zhokhov.graphql",
          "module": "graphql-java-datetime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-security-0.4.2-plain.jar",
          "url": "graphql-kotlin-spring-security-0.4.2-plain.jar",
          "size": 12586,
          "sha512": "b81bb47088a54579cd82fd3928707de7607431f101c3ceb89ca3e0e4fa1845c25dc81dfe41b5e0e7aed05f94376e8d60f5be158e98aebce736eb05c1de576937",
          "sha256": "058625db374fbb24cab805f9d9a5dc872842211c2a044fddee931df50d8ef1fb",
          "sha1": "e84c3eb996f3b5770d0af05aa601540b162b1e72",
          "md5": "5cbed1c23f91d33e7a50482c316400ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        },
        {
          "group": "com.zhokhov.graphql",
          "module": "graphql-java-datetime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-security-0.4.2-plain.jar",
          "url": "graphql-kotlin-spring-security-0.4.2-plain.jar",
          "size": 12586,
          "sha512": "b81bb47088a54579cd82fd3928707de7607431f101c3ceb89ca3e0e4fa1845c25dc81dfe41b5e0e7aed05f94376e8d60f5be158e98aebce736eb05c1de576937",
          "sha256": "058625db374fbb24cab805f9d9a5dc872842211c2a044fddee931df50d8ef1fb",
          "sha1": "e84c3eb996f3b5770d0af05aa601540b162b1e72",
          "md5": "5cbed1c23f91d33e7a50482c316400ec"
        }
      ]
    }
  ]
}
