{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-jetpack-starter",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-jetpack-autoconfigure",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-hooks-provider",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-security-jwt-webflux",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-starter-0.5.0-plain.jar",
          "url": "graphql-jetpack-starter-0.5.0-plain.jar",
          "size": 261,
          "sha512": "849bd1e5766958346408608b917ff3733e652ad988516b2819545dada56423754b5b9144320b91551a966523d813b5b639085659a692c647a229dafda1e6ffef",
          "sha256": "da5f135203469e9471b8600ff6575f4e627d21b12cd6812114b6444ed6d19e6e",
          "sha1": "b10c67962e2de5bb4b0b8e1b32a0feb515ab9fd4",
          "md5": "27258d4064aa3d3dbd1622784fc8a2d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-jetpack-autoconfigure",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-hooks-provider",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-security-jwt-webflux",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-starter-0.5.0-plain.jar",
          "url": "graphql-jetpack-starter-0.5.0-plain.jar",
          "size": 261,
          "sha512": "849bd1e5766958346408608b917ff3733e652ad988516b2819545dada56423754b5b9144320b91551a966523d813b5b639085659a692c647a229dafda1e6ffef",
          "sha256": "da5f135203469e9471b8600ff6575f4e627d21b12cd6812114b6444ed6d19e6e",
          "sha1": "b10c67962e2de5bb4b0b8e1b32a0feb515ab9fd4",
          "md5": "27258d4064aa3d3dbd1622784fc8a2d6"
        }
      ]
    }
  ]
}
