{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc-autoconfigure",
    "version": "0.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.4.7-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.4.7-plain.jar",
          "size": 14677,
          "sha512": "36d9ff349b8ee31ae07c2becb03147cfc986d049ec6bf060264d72dca9ed142dbd6d684f479e48374d0076c7b6fc831d15d057b0524fb2ae4a419c08fca8a98f",
          "sha256": "3c201ac99a9433a2e92ed499b008812c4e545d32d48b757e27e3b4da03f22395",
          "sha1": "134ac7c134fc826ab590070337f2b4199a2de593",
          "md5": "764af3dbc7a13772544d5c7aa2ac3df7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.4.7-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.4.7-plain.jar",
          "size": 14677,
          "sha512": "36d9ff349b8ee31ae07c2becb03147cfc986d049ec6bf060264d72dca9ed142dbd6d684f479e48374d0076c7b6fc831d15d057b0524fb2ae4a419c08fca8a98f",
          "sha256": "3c201ac99a9433a2e92ed499b008812c4e545d32d48b757e27e3b4da03f22395",
          "sha1": "134ac7c134fc826ab590070337f2b4199a2de593",
          "md5": "764af3dbc7a13772544d5c7aa2ac3df7"
        }
      ]
    }
  ]
}
