{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-postgresql-scalars",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.8.10.RELEASE"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-postgresql-scalars-0.5.4.jar",
          "url": "graphql-postgresql-scalars-0.5.4.jar",
          "size": 10826,
          "sha512": "1e55e63a561a27e28da380802701153e5f73eb29f75ea96221ff023730776fb9d00c7d29791b7dfb37ff0afe730858e0785e84ad68af47838b92ede544b5702a",
          "sha256": "fa936e8b0f4141fa3893d661a1a5125e6f9eb9925381a8062ef486c2bfc793b4",
          "sha1": "535ccccd2119bcdf4df39df92abc12710bba7342",
          "md5": "4231a1f0b67d179bb1987db57030099f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.4"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.8.10.RELEASE"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-postgresql-scalars-0.5.4.jar",
          "url": "graphql-postgresql-scalars-0.5.4.jar",
          "size": 10826,
          "sha512": "1e55e63a561a27e28da380802701153e5f73eb29f75ea96221ff023730776fb9d00c7d29791b7dfb37ff0afe730858e0785e84ad68af47838b92ede544b5702a",
          "sha256": "fa936e8b0f4141fa3893d661a1a5125e6f9eb9925381a8062ef486c2bfc793b4",
          "sha1": "535ccccd2119bcdf4df39df92abc12710bba7342",
          "md5": "4231a1f0b67d179bb1987db57030099f"
        }
      ]
    }
  ]
}
