{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-kotlin-spring-security",
    "version": "0.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        },
        {
          "group": "com.zhokhov.graphql",
          "module": "graphql-java-datetime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-security-0.5.6-plain.jar",
          "url": "graphql-kotlin-spring-security-0.5.6-plain.jar",
          "size": 12775,
          "sha512": "91db10231ad43fe15fdddbc1a81aa73759c5c888fb73cbd5b48db8c7b36c4aa77feab021de6889569a5dadc3b3d9347b150d96dad55d5b2768b39d0cb8260763",
          "sha256": "2641efd6326b03c30d6c1fa8d672d29e53cd451901c0895d3d9b09df0e773f59",
          "sha1": "19fa328bd7b03236bafe25506ff4b36901004cd8",
          "md5": "df6dc14c98d8c5535ef748459a5e465d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        },
        {
          "group": "com.zhokhov.graphql",
          "module": "graphql-java-datetime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-security-0.5.6-plain.jar",
          "url": "graphql-kotlin-spring-security-0.5.6-plain.jar",
          "size": 12775,
          "sha512": "91db10231ad43fe15fdddbc1a81aa73759c5c888fb73cbd5b48db8c7b36c4aa77feab021de6889569a5dadc3b3d9347b150d96dad55d5b2768b39d0cb8260763",
          "sha256": "2641efd6326b03c30d6c1fa8d672d29e53cd451901c0895d3d9b09df0e773f59",
          "sha1": "19fa328bd7b03236bafe25506ff4b36901004cd8",
          "md5": "df6dc14c98d8c5535ef748459a5e465d"
        }
      ]
    }
  ]
}
