{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-core",
    "version": "0.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-core-0.4.7.jar",
          "url": "graphql-core-0.4.7.jar",
          "size": 79876,
          "sha512": "d9eba2699dea0a96b8b6c088a6bb88d673079180cf2207c67fad315575113c79dd5cc2926478dcc0399a3e6faa5a43a12720c71aaab40cb3f86df675d77eb716",
          "sha256": "1f09d92a8186e718241876ee59f9d3e75ba5cecc3341109f1e740d95859a4392",
          "sha1": "fe47bf5a6cc8c871ccf421b2d31a96af21606fc2",
          "md5": "234714ae3ad684e98b11d7efc9675e95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-core-0.4.7.jar",
          "url": "graphql-core-0.4.7.jar",
          "size": 79876,
          "sha512": "d9eba2699dea0a96b8b6c088a6bb88d673079180cf2207c67fad315575113c79dd5cc2926478dcc0399a3e6faa5a43a12720c71aaab40cb3f86df675d77eb716",
          "sha256": "1f09d92a8186e718241876ee59f9d3e75ba5cecc3341109f1e740d95859a4392",
          "sha1": "fe47bf5a6cc8c871ccf421b2d31a96af21606fc2",
          "md5": "234714ae3ad684e98b11d7efc9675e95"
        }
      ]
    }
  ]
}
