{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-jetpack-starter",
    "version": "0.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-jetpack-autoconfigure",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-hooks-provider",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-security-jwt-webflux",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-starter-0.5.7-plain.jar",
          "url": "graphql-jetpack-starter-0.5.7-plain.jar",
          "size": 261,
          "sha512": "7cf705e2970ff1dcc58f405e231ef0f97d7a765de43b695c43774a74e37d635a33788b4ed634af28b53fa2980ab0ab4edf4cf4a6d4b2c57902c70a7cbfc0d9c7",
          "sha256": "6de77195ac97cf5f5a2e45d221ac61e25420d398a87f449faceea53a57dc0bc7",
          "sha1": "2887f74e799f56cc7e2210cd7b2b350e181c0119",
          "md5": "1b8e7ab725239413c9c88fa61e1566a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-jetpack-autoconfigure",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-hooks-provider",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-security-jwt-webflux",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-starter-0.5.7-plain.jar",
          "url": "graphql-jetpack-starter-0.5.7-plain.jar",
          "size": 261,
          "sha512": "7cf705e2970ff1dcc58f405e231ef0f97d7a765de43b695c43774a74e37d635a33788b4ed634af28b53fa2980ab0ab4edf4cf4a6d4b2c57902c70a7cbfc0d9c7",
          "sha256": "6de77195ac97cf5f5a2e45d221ac61e25420d398a87f449faceea53a57dc0bc7",
          "sha1": "2887f74e799f56cc7e2210cd7b2b350e181c0119",
          "md5": "1b8e7ab725239413c9c88fa61e1566a2"
        }
      ]
    }
  ]
}
