/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.wickedev.graphql.spring.data.r2dbc

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
