{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc-starter",
    "version": "0.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc-autoconfigure",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-starter-0.4.7-plain.jar",
          "url": "spring-data-graphql-r2dbc-starter-0.4.7-plain.jar",
          "size": 261,
          "sha512": "11ba14c07646174e829310c4331a3280b7332f47377edbe0dee3349355d955f826c616c29c7d35fe76fa6d1f1b66ea33adcc33e8f898bec2dd1bfba96782f446",
          "sha256": "7879840c504001f75f5f1e3126c55351b2666d3f81745e823284d0c67a6957f7",
          "sha1": "114e020c3353eb08ab4395760a7fd9766026df13",
          "md5": "820c265e106bd3f0a435dfd30d2abf08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc-autoconfigure",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-starter-0.4.7-plain.jar",
          "url": "spring-data-graphql-r2dbc-starter-0.4.7-plain.jar",
          "size": 261,
          "sha512": "11ba14c07646174e829310c4331a3280b7332f47377edbe0dee3349355d955f826c616c29c7d35fe76fa6d1f1b66ea33adcc33e8f898bec2dd1bfba96782f446",
          "sha256": "7879840c504001f75f5f1e3126c55351b2666d3f81745e823284d0c67a6957f7",
          "sha1": "114e020c3353eb08ab4395760a7fd9766026df13",
          "md5": "820c265e106bd3f0a435dfd30d2abf08"
        }
      ]
    }
  ]
}
