{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-jetpack-autoconfigure",
    "version": "0.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-jetpack",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-kotlin-spring-security",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-kotlin-spring-webflux-upload",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-autoconfigure-0.5.7-plain.jar",
          "url": "graphql-jetpack-autoconfigure-0.5.7-plain.jar",
          "size": 10825,
          "sha512": "5b444595a324566ef634d342788b5667453b1930334aa30d24e43ac2f878a6d3ef0ec23aade0b6d58897a10bcad2c195e2fe9c234c660b2bbf5d804675db537e",
          "sha256": "74fb5c435fd388d73871af4db44a74e5ee2289f7ee3d07b790192f8cee64d79a",
          "sha1": "ac4a785523b962755966274a0abb39604f96393d",
          "md5": "a4a1bb62a5249f764476eb6935fbcae9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-jetpack",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-kotlin-spring-security",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-kotlin-spring-webflux-upload",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-hooks-provider",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-security-jwt-webflux",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-autoconfigure-0.5.7-plain.jar",
          "url": "graphql-jetpack-autoconfigure-0.5.7-plain.jar",
          "size": 10825,
          "sha512": "5b444595a324566ef634d342788b5667453b1930334aa30d24e43ac2f878a6d3ef0ec23aade0b6d58897a10bcad2c195e2fe9c234c660b2bbf5d804675db537e",
          "sha256": "74fb5c435fd388d73871af4db44a74e5ee2289f7ee3d07b790192f8cee64d79a",
          "sha1": "ac4a785523b962755966274a0abb39604f96393d",
          "md5": "a4a1bb62a5249f764476eb6935fbcae9"
        }
      ]
    }
  ]
}
