{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-postgresql-scalars",
    "version": "0.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.8.10.RELEASE"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-postgresql-scalars-0.5.6.jar",
          "url": "graphql-postgresql-scalars-0.5.6.jar",
          "size": 10826,
          "sha512": "f7fdf0269c1d0d078d26efb9f40373d8dc4d063a7c5f44f9f0c7c2ceba0ce1f7947db63f1477561f4a887423b2b4706f536d8c1f041799bdf7a20945a7bb741c",
          "sha256": "605de44036fdb2f2f8166af13dc66a6205f719ae9d8cad81887c7d14d26fc95e",
          "sha1": "240017adaf8e30c7b70af21e8e8e2eab0f6c5ba1",
          "md5": "03bc38d6e8629373bd0d84aadfe01a3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.8.10.RELEASE"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-postgresql-scalars-0.5.6.jar",
          "url": "graphql-postgresql-scalars-0.5.6.jar",
          "size": 10826,
          "sha512": "f7fdf0269c1d0d078d26efb9f40373d8dc4d063a7c5f44f9f0c7c2ceba0ce1f7947db63f1477561f4a887423b2b4706f536d8c1f041799bdf7a20945a7bb741c",
          "sha256": "605de44036fdb2f2f8166af13dc66a6205f719ae9d8cad81887c7d14d26fc95e",
          "sha1": "240017adaf8e30c7b70af21e8e8e2eab0f6c5ba1",
          "md5": "03bc38d6e8629373bd0d84aadfe01a3b"
        }
      ]
    }
  ]
}
