{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-postgresql-scalars",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.8.10.RELEASE"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-postgresql-scalars-0.4.5.jar",
          "url": "graphql-postgresql-scalars-0.4.5.jar",
          "size": 10826,
          "sha512": "bdd26562fcf9db71133a1c68ad576d59c0078d11064b6b7fa5ceed211de541f056fdda62b45d69fac8acca754ed62b3b04355e2ed22a42c658626bb29ac3c1a6",
          "sha256": "59a3b36577dd8cf056ae63c27b8e83f233ea454bd5699abab9226ac281589c2f",
          "sha1": "95c56e7c4630b59d9c353eeddbc4c9538377c234",
          "md5": "47a9f21a1a5293224b4f6aedbffdf7ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.8.10.RELEASE"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java-extended-scalars",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-postgresql-scalars-0.4.5.jar",
          "url": "graphql-postgresql-scalars-0.4.5.jar",
          "size": 10826,
          "sha512": "bdd26562fcf9db71133a1c68ad576d59c0078d11064b6b7fa5ceed211de541f056fdda62b45d69fac8acca754ed62b3b04355e2ed22a42c658626bb29ac3c1a6",
          "sha256": "59a3b36577dd8cf056ae63c27b8e83f233ea454bd5699abab9226ac281589c2f",
          "sha1": "95c56e7c4630b59d9c353eeddbc4c9538377c234",
          "md5": "47a9f21a1a5293224b4f6aedbffdf7ac"
        }
      ]
    }
  ]
}
