{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-kotlin-spring-webflux-upload",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux"
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-webflux-upload-0.4.1-plain.jar",
          "url": "graphql-kotlin-spring-webflux-upload-0.4.1-plain.jar",
          "size": 24252,
          "sha512": "c67d03d9fa66219074e7a61a5450696daa75656bbf432490beca28e2626d7de42305ee507ff2830b49f7f36f82d724d706e8f6dab5ba484abc05e1b8b790ba94",
          "sha256": "4b596c8c1d1a5bc1fdc9afa7ffd02b7dc46689c492477ac1849a769f68510562",
          "sha1": "9880fde95cead48e0d51539b286e56677af84603",
          "md5": "46f95e1997bae466ac0f8ed2321f4946"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux"
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-webflux-upload-0.4.1-plain.jar",
          "url": "graphql-kotlin-spring-webflux-upload-0.4.1-plain.jar",
          "size": 24252,
          "sha512": "c67d03d9fa66219074e7a61a5450696daa75656bbf432490beca28e2626d7de42305ee507ff2830b49f7f36f82d724d706e8f6dab5ba484abc05e1b8b790ba94",
          "sha256": "4b596c8c1d1a5bc1fdc9afa7ffd02b7dc46689c492477ac1849a769f68510562",
          "sha1": "9880fde95cead48e0d51539b286e56677af84603",
          "md5": "46f95e1997bae466ac0f8ed2321f4946"
        }
      ]
    }
  ]
}
