{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-kotlin-spring-security",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        },
        {
          "group": "com.zhokhov.graphql",
          "module": "graphql-java-datetime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-security-0.5.0-plain.jar",
          "url": "graphql-kotlin-spring-security-0.5.0-plain.jar",
          "size": 12586,
          "sha512": "f54254d643db9951d0e9a9c2f83e7322d0e05a03499477291cf390ae8966e2ad7515ff0d9573b6b117fe43ecdee80d86077799768db3b8d9c5bdc469cfd31c6c",
          "sha256": "b1521cb9cedb885a316ed15131f3588fd68b81e2c8de1260d9060fb5e0413f0f",
          "sha1": "f6370347d69436787af95a22fb828f87d3b50a29",
          "md5": "c64cf0678cf290d5d763065735c7dd8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        },
        {
          "group": "com.zhokhov.graphql",
          "module": "graphql-java-datetime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-security-0.5.0-plain.jar",
          "url": "graphql-kotlin-spring-security-0.5.0-plain.jar",
          "size": 12586,
          "sha512": "f54254d643db9951d0e9a9c2f83e7322d0e05a03499477291cf390ae8966e2ad7515ff0d9573b6b117fe43ecdee80d86077799768db3b8d9c5bdc469cfd31c6c",
          "sha256": "b1521cb9cedb885a316ed15131f3588fd68b81e2c8de1260d9060fb5e0413f0f",
          "sha1": "f6370347d69436787af95a22fb828f87d3b50a29",
          "md5": "c64cf0678cf290d5d763065735c7dd8a"
        }
      ]
    }
  ]
}
