{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "kotlin-coroutine-reactive-extensions",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-coroutine-reactive-extensions-0.5.3.jar",
          "url": "kotlin-coroutine-reactive-extensions-0.5.3.jar",
          "size": 8778,
          "sha512": "db0b989e487753f262ff2561897cbf2136d4e6aed238a4f25e262ed6ff2fa67ae2b1827bb9d4a6ae101101471397cbf2d841bc6382e99be4346d61d972533c96",
          "sha256": "5e6ffa6f6b8d4dcf68d3067b8b2ea3ecbaecb5c118980dd6038246bbe3a99f18",
          "sha1": "20824150c645237b214676743a9efc9bcdd68173",
          "md5": "d28e8ff25b531c4c67cf3d801e9899fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-coroutine-reactive-extensions-0.5.3.jar",
          "url": "kotlin-coroutine-reactive-extensions-0.5.3.jar",
          "size": 8778,
          "sha512": "db0b989e487753f262ff2561897cbf2136d4e6aed238a4f25e262ed6ff2fa67ae2b1827bb9d4a6ae101101471397cbf2d841bc6382e99be4346d61d972533c96",
          "sha256": "5e6ffa6f6b8d4dcf68d3067b8b2ea3ecbaecb5c118980dd6038246bbe3a99f18",
          "sha1": "20824150c645237b214676743a9efc9bcdd68173",
          "md5": "d28e8ff25b531c4c67cf3d801e9899fa"
        }
      ]
    }
  ]
}
