{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "kotlin-coroutine-reactive-extensions",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-coroutine-reactive-extensions-0.5.4.jar",
          "url": "kotlin-coroutine-reactive-extensions-0.5.4.jar",
          "size": 8778,
          "sha512": "70695ca24ef90a12591ecf18dd6e692632f7f5c9aee70c0b8e5804ac16f93d5f759da8a113ba690e762773177c893fff454b734d831c802c935cffd506ef3214",
          "sha256": "e0fe0483019fb13b40e552fe457c0aa7c2e82a34bcfe922ed3741d2faf40d647",
          "sha1": "616961e2afbdd56e8b9b3419df204444cc5a9e6b",
          "md5": "a8d535743f3119ad7ff1ea1fba6bcab4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-coroutine-reactive-extensions-0.5.4.jar",
          "url": "kotlin-coroutine-reactive-extensions-0.5.4.jar",
          "size": 8778,
          "sha512": "70695ca24ef90a12591ecf18dd6e692632f7f5c9aee70c0b8e5804ac16f93d5f759da8a113ba690e762773177c893fff454b734d831c802c935cffd506ef3214",
          "sha256": "e0fe0483019fb13b40e552fe457c0aa7c2e82a34bcfe922ed3741d2faf40d647",
          "sha1": "616961e2afbdd56e8b9b3419df204444cc5a9e6b",
          "md5": "a8d535743f3119ad7ff1ea1fba6bcab4"
        }
      ]
    }
  ]
}
