{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc-autoconfigure",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.5.0-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.5.0-plain.jar",
          "size": 14677,
          "sha512": "1e8473fc2e1fd133043246810e0652e38164d649370dd2370de1dd9a1f77b25b0f7be7fb33593b3440cc3fed43e747a68f45fb034c4d14cbdece137ad48fa1f0",
          "sha256": "69f7b95e7c4d4f6ec100ca62041adaf1b87aca70a2c9c08083e389ffea1511b1",
          "sha1": "372ec7e757bbe020b68064642fea3a982194af44",
          "md5": "c5b758f2f1b57a95cf244dbaf2388129"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.5.0-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.5.0-plain.jar",
          "size": 14677,
          "sha512": "1e8473fc2e1fd133043246810e0652e38164d649370dd2370de1dd9a1f77b25b0f7be7fb33593b3440cc3fed43e747a68f45fb034c4d14cbdece137ad48fa1f0",
          "sha256": "69f7b95e7c4d4f6ec100ca62041adaf1b87aca70a2c9c08083e389ffea1511b1",
          "sha1": "372ec7e757bbe020b68064642fea3a982194af44",
          "md5": "c5b758f2f1b57a95cf244dbaf2388129"
        }
      ]
    }
  ]
}
