{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc-autoconfigure",
    "version": "0.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.5.8-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.5.8-plain.jar",
          "size": 14677,
          "sha512": "215d08d594ff9ba69f613eb5a642d7f3558ae6cdd3d27fbf3a53b05433fa5a500545184d0839cd931ab1ef1b372f89a058ca27590e92ffe32dec98da2d0b2333",
          "sha256": "bb147d4264971656de7dffe0f7e6701b71ea9cc0b7b748009379e70727cece7f",
          "sha1": "ca905d1f2fdd936028b1d12f56aca56c931b6a79",
          "md5": "b24f5758b87f748bd3070e4be3fa2518"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.5.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.5.8-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.5.8-plain.jar",
          "size": 14677,
          "sha512": "215d08d594ff9ba69f613eb5a642d7f3558ae6cdd3d27fbf3a53b05433fa5a500545184d0839cd931ab1ef1b372f89a058ca27590e92ffe32dec98da2d0b2333",
          "sha256": "bb147d4264971656de7dffe0f7e6701b71ea9cc0b7b748009379e70727cece7f",
          "sha1": "ca905d1f2fdd936028b1d12f56aca56c931b6a79",
          "md5": "b24f5758b87f748bd3070e4be3fa2518"
        }
      ]
    }
  ]
}
