{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-commons",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "java-dataloader",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-0.4.0-plain.jar",
          "url": "spring-data-graphql-r2dbc-0.4.0-plain.jar",
          "size": 218133,
          "sha512": "5e8ecb2e149614fd824647e2ff8e2e76c8292eb3f9b2276f38a0f54785e9658a91e705f351283445283ea7e3ce549f088932dc7d183863cb3d04b1769241d150",
          "sha256": "d5129f3a40ac68e8068062b9bcc43b410aed06832b1744f10d62e724ac6add33",
          "sha1": "1a389a138056a5719ac564616601d85bd1298208",
          "md5": "4e52c9be8168014cf07a20b3b92c2e74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-commons",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "java-dataloader",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-0.4.0-plain.jar",
          "url": "spring-data-graphql-r2dbc-0.4.0-plain.jar",
          "size": 218133,
          "sha512": "5e8ecb2e149614fd824647e2ff8e2e76c8292eb3f9b2276f38a0f54785e9658a91e705f351283445283ea7e3ce549f088932dc7d183863cb3d04b1769241d150",
          "sha256": "d5129f3a40ac68e8068062b9bcc43b410aed06832b1744f10d62e724ac6add33",
          "sha1": "1a389a138056a5719ac564616601d85bd1298208",
          "md5": "4e52c9be8168014cf07a20b3b92c2e74"
        }
      ]
    }
  ]
}
