{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc-autoconfigure",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.4.6-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.4.6-plain.jar",
          "size": 14677,
          "sha512": "f6f8e893e247495022c261389eee4a74b9490fe5a948999e60387e97525652e05a9c26dba4092b04315f8e4ec8e8b252bab6d06806ab5f75cb0e29ffba34181c",
          "sha256": "5a9ad114631a2800bd5b954fa7c47a99c2777bd2dd476bb228c3b80032f64a12",
          "sha1": "8613e631c948ede062cff6a5cf4d132b604edd1c",
          "md5": "8e29eec72bc05b3cd2c3f9d91fdd225d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.4.6-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.4.6-plain.jar",
          "size": 14677,
          "sha512": "f6f8e893e247495022c261389eee4a74b9490fe5a948999e60387e97525652e05a9c26dba4092b04315f8e4ec8e8b252bab6d06806ab5f75cb0e29ffba34181c",
          "sha256": "5a9ad114631a2800bd5b954fa7c47a99c2777bd2dd476bb228c3b80032f64a12",
          "sha1": "8613e631c948ede062cff6a5cf4d132b604edd1c",
          "md5": "8e29eec72bc05b3cd2c3f9d91fdd225d"
        }
      ]
    }
  ]
}
