{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "spring-data-graphql-r2dbc-autoconfigure",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.4.1-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.4.1-plain.jar",
          "size": 14677,
          "sha512": "d5d85579c5b6c36804a93ba47a10f09e7aa68a967236c8df0c2d334464ebc5a6ed074c7e59225db6b874aa98472318bde27764eb93802ed264cbf2efcf052611",
          "sha256": "4c31211c522ec1a3580dcf72319d7a3e4fb8526a8c2ed6afcb636d05e288a0bf",
          "sha1": "04dc517e2e54ea07f22d47eb0609cf662b4ccbbf",
          "md5": "5dc705328846f25fccf85f99269d8112"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "spring-data-graphql-r2dbc",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-r2dbc"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        }
      ],
      "files": [
        {
          "name": "spring-data-graphql-r2dbc-autoconfigure-0.4.1-plain.jar",
          "url": "spring-data-graphql-r2dbc-autoconfigure-0.4.1-plain.jar",
          "size": 14677,
          "sha512": "d5d85579c5b6c36804a93ba47a10f09e7aa68a967236c8df0c2d334464ebc5a6ed074c7e59225db6b874aa98472318bde27764eb93802ed264cbf2efcf052611",
          "sha256": "4c31211c522ec1a3580dcf72319d7a3e4fb8526a8c2ed6afcb636d05e288a0bf",
          "sha1": "04dc517e2e54ea07f22d47eb0609cf662b4ccbbf",
          "md5": "5dc705328846f25fccf85f99269d8112"
        }
      ]
    }
  ]
}
