{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-jetpack",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-kotlin-spring-security",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-0.5.0-plain.jar",
          "url": "graphql-jetpack-0.5.0-plain.jar",
          "size": 15404,
          "sha512": "77684c0c07c4ed77740b7c5a71c0a3f4d41de9ddf2b4055c31353205fc7df319b01a31f2e04de02b9649a6f6607e51247ff4fa18c2a95b4b1390ceef79370815",
          "sha256": "3abaed9cc520b008914e76a18c120e6ade252d63caef09d0cbbc0a73c95ec7a6",
          "sha1": "1de05692af3287ca6d01208cb420f95d4c3c7635",
          "md5": "b32f50069beda6b71686668a61a446e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-kotlin-spring-security",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        }
      ],
      "files": [
        {
          "name": "graphql-jetpack-0.5.0-plain.jar",
          "url": "graphql-jetpack-0.5.0-plain.jar",
          "size": 15404,
          "sha512": "77684c0c07c4ed77740b7c5a71c0a3f4d41de9ddf2b4055c31353205fc7df319b01a31f2e04de02b9649a6f6607e51247ff4fa18c2a95b4b1390ceef79370815",
          "sha256": "3abaed9cc520b008914e76a18c120e6ade252d63caef09d0cbbc0a73c95ec7a6",
          "sha1": "1de05692af3287ca6d01208cb420f95d4c3c7635",
          "md5": "b32f50069beda6b71686668a61a446e9"
        }
      ]
    }
  ]
}
