{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-kotlin-spring-security",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        },
        {
          "group": "com.zhokhov.graphql",
          "module": "graphql-java-datetime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-security-0.5.1-plain.jar",
          "url": "graphql-kotlin-spring-security-0.5.1-plain.jar",
          "size": 12586,
          "sha512": "416ac11c8c15a0f874e84066cc983bdddbc002bf9a765dc1e63566ae5e67996c61a63451d013bfe0dba516bf2e0e1a9aece7118d68d3b21effe9567bab3f6282",
          "sha256": "349074518a4e6b627eb39d27c6844df73584aba9ec915e0deaec0bc294f174df",
          "sha1": "c2101249badc7b9f7b3789836479661082c34ff3",
          "md5": "5f7320101b2522cef7801feb6dfd1261"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "graphql-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "io.github.wickedev",
          "module": "kotlin-coroutine-reactive-extensions",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.expediagroup",
          "module": "graphql-kotlin-spring-server",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core"
        },
        {
          "group": "com.zhokhov.graphql",
          "module": "graphql-java-datetime",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        }
      ],
      "files": [
        {
          "name": "graphql-kotlin-spring-security-0.5.1-plain.jar",
          "url": "graphql-kotlin-spring-security-0.5.1-plain.jar",
          "size": 12586,
          "sha512": "416ac11c8c15a0f874e84066cc983bdddbc002bf9a765dc1e63566ae5e67996c61a63451d013bfe0dba516bf2e0e1a9aece7118d68d3b21effe9567bab3f6282",
          "sha256": "349074518a4e6b627eb39d27c6844df73584aba9ec915e0deaec0bc294f174df",
          "sha1": "c2101249badc7b9f7b3789836479661082c34ff3",
          "md5": "5f7320101b2522cef7801feb6dfd1261"
        }
      ]
    }
  ]
}
