{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-core",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-core-0.4.1.jar",
          "url": "graphql-core-0.4.1.jar",
          "size": 46424,
          "sha512": "34d4fa06a93c82081cf23adeceef9f7e74785498be46353aaf9a59b0ea32e1f85bf25e9ca544adc475452ce00148f0bf31a554be29056235e95012bc84d31f59",
          "sha256": "44b1f192c57f47e20bcc51057dcc724d594e0cc5bb31b9cf284aeb5a26d9fd2a",
          "sha1": "36dd1ce452dc4a363b7d132d7bd7c5c3f52125dc",
          "md5": "51eec5edda38a31f94b51c47be8b64c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-core-0.4.1.jar",
          "url": "graphql-core-0.4.1.jar",
          "size": 46424,
          "sha512": "34d4fa06a93c82081cf23adeceef9f7e74785498be46353aaf9a59b0ea32e1f85bf25e9ca544adc475452ce00148f0bf31a554be29056235e95012bc84d31f59",
          "sha256": "44b1f192c57f47e20bcc51057dcc724d594e0cc5bb31b9cf284aeb5a26d9fd2a",
          "sha1": "36dd1ce452dc4a363b7d132d7bd7c5c3f52125dc",
          "md5": "51eec5edda38a31f94b51c47be8b64c5"
        }
      ]
    }
  ]
}
