{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.wickedev",
    "module": "graphql-core",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-core-0.4.0.jar",
          "url": "graphql-core-0.4.0.jar",
          "size": 46424,
          "sha512": "d351e36880b14fc02ee0da6aec43cf8e6f915e12d5cb437782a5620911ab25cdff42604cb10d7d05687a80ba38230fe1d668c381f2906906d4e6aedb9760b05a",
          "sha256": "37935dd208c11124b687f0268ce4c323dc7a66ae4f85824b9558a424856edff5",
          "sha1": "0560628eddb5ff7afbbf9661506ec673b5427955",
          "md5": "f846a505cfb1076f1f4b3132211b930b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.graphql-java",
          "module": "graphql-java",
          "version": {
            "requires": "17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "graphql-core-0.4.0.jar",
          "url": "graphql-core-0.4.0.jar",
          "size": 46424,
          "sha512": "d351e36880b14fc02ee0da6aec43cf8e6f915e12d5cb437782a5620911ab25cdff42604cb10d7d05687a80ba38230fe1d668c381f2906906d4e6aedb9760b05a",
          "sha256": "37935dd208c11124b687f0268ce4c323dc7a66ae4f85824b9558a424856edff5",
          "sha1": "0560628eddb5ff7afbbf9661506ec673b5427955",
          "md5": "f846a505cfb1076f1f4b3132211b930b"
        }
      ]
    }
  ]
}
